name: CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy-Frontend
        run: |
          SYSTEM="$(cut -d'-' -f1 <<< ${GITHUB_REF/refs\/tags\//})"
          if ["$SYSTEM" == "frontend"]; then
            VERSION="$(cut -d'-' -f2 <<< ${GITHUB_REF/refs\/tags\//})"
            echo "$VERSION"
            #sshpass -p ${{ secrets.pw }} ssh root@dhbw-richie.de DOCKER_TAG=$VERSION -o StrictHostKeyChecking=no < ./deploy/deploy-frontend.bash
          else
            echo "Skipped because tag was not matching"
          fi
      - name: Deploy-Backend
        run: |
          if ["$SYSTEM" == "backend"]; then
            VERSION="$(cut -d'-' -f2 <<< ${GITHUB_REF/refs\/tags\//})"
            #sshpass -p ${{ secrets.pw }} ssh root@dhbw-richie.de DOCKER_TAG=$VERSION -o StrictHostKeyChecking=no < ./deploy/deploy-backend.bash
          else
            echo "Skipped because tag was not matching"
          fi
